version: '3.1'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pqv-yue6ztr7ADB@gma
      MYSQL_DATABASE: treact
      MYSQL_USER: treact
      MYSQL_PASSWORD: BXA*bqn*kyx7vjm5fbx
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - localnetwork

volumes:
  mysql_data:

networks:
  localnetwork:
    driver: bridge